server:
  port: 80
  session:
    timeout: 600
spring:
  redis:
    host: localhost
    port: 6380
  session:
    store-type: redis
#logging:
#  pattern:
#    console: "%d - %msg%n"
##  path: D:/log/
#  file: D:/log/logback.log
#  level: debug
merryyou:
  security:
    code:
      image:
        width: 90
        height: 20
        length: 4
        expireIn: 30
        url: /code/*
    session:
      maximumSessions: 1
      maxSessionsPreventsLogin: false
#      sessionInvalidUrl : /merryyou-session-invalid.html
    loginType: JSON